### PR TITLE
Preliminary Keystone V3 support

### PR DESCRIPTION
**Pull request by enolfc**

### CODE REVIEW

**Comment by arax** [comment]
I presume this change has been tested, right? On multiple sites, with multiple OS versions? Just checking :-)

**Comment by enolfc** [comment]
The change was tested with a mocked keystone. Before merging it should be properly tested with actual OS.

**Comment by arax** [comment]
Ok. Is this something that should be pushed to a stable release quickly?

**Comment by enolfc** [comment]
No, we don't have (yet) any Keystone-V3 + VOMS.

**Comment by arax** [comment]
:+1: I will leave this PR open and merge it after a few real-world tests then.

**Pull request merged**
